// Code generated by "enumer -type FrameType -text -values -json -trimprefix FrameType -output types_string.go"; DO NOT EDIT.

package websocket

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	_FrameTypeName_0      = "NoFrame"
	_FrameTypeLowerName_0 = "noframe"
	_FrameTypeName_1      = "TextBinary"
	_FrameTypeLowerName_1 = "textbinary"
	_FrameTypeName_2      = "ClosePingPong"
	_FrameTypeLowerName_2 = "closepingpong"
)

var (
	_FrameTypeIndex_0 = [...]uint8{0, 7}
	_FrameTypeIndex_1 = [...]uint8{0, 4, 10}
	_FrameTypeIndex_2 = [...]uint8{0, 5, 9, 13}
)

func (i FrameType) String() string {
	switch {
	case i == -1:
		return _FrameTypeName_0
	case 1 <= i && i <= 2:
		i -= 1
		return _FrameTypeName_1[_FrameTypeIndex_1[i]:_FrameTypeIndex_1[i+1]]
	case 9 <= i && i <= 11:
		i -= 9
		return _FrameTypeName_2[_FrameTypeIndex_2[i]:_FrameTypeIndex_2[i+1]]
	default:
		return fmt.Sprintf("FrameType(%d)", i)
	}
}

func (FrameType) Values() []string {
	return FrameTypeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FrameTypeNoOp() {
	var x [1]struct{}
	_ = x[FrameTypeNoFrame-(-1)]
	_ = x[FrameTypeText-(1)]
	_ = x[FrameTypeBinary-(2)]
	_ = x[FrameTypeClose-(9)]
	_ = x[FrameTypePing-(10)]
	_ = x[FrameTypePong-(11)]
}

var _FrameTypeValues = []FrameType{FrameTypeNoFrame, FrameTypeText, FrameTypeBinary, FrameTypeClose, FrameTypePing, FrameTypePong}

var _FrameTypeNameToValueMap = map[string]FrameType{
	_FrameTypeName_0[0:7]:       FrameTypeNoFrame,
	_FrameTypeLowerName_0[0:7]:  FrameTypeNoFrame,
	_FrameTypeName_1[0:4]:       FrameTypeText,
	_FrameTypeLowerName_1[0:4]:  FrameTypeText,
	_FrameTypeName_1[4:10]:      FrameTypeBinary,
	_FrameTypeLowerName_1[4:10]: FrameTypeBinary,
	_FrameTypeName_2[0:5]:       FrameTypeClose,
	_FrameTypeLowerName_2[0:5]:  FrameTypeClose,
	_FrameTypeName_2[5:9]:       FrameTypePing,
	_FrameTypeLowerName_2[5:9]:  FrameTypePing,
	_FrameTypeName_2[9:13]:      FrameTypePong,
	_FrameTypeLowerName_2[9:13]: FrameTypePong,
}

var _FrameTypeNames = []string{
	_FrameTypeName_0[0:7],
	_FrameTypeName_1[0:4],
	_FrameTypeName_1[4:10],
	_FrameTypeName_2[0:5],
	_FrameTypeName_2[5:9],
	_FrameTypeName_2[9:13],
}

// FrameTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FrameTypeString(s string) (FrameType, error) {
	if val, ok := _FrameTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FrameTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FrameType values", s)
}

// FrameTypeValues returns all values of the enum
func FrameTypeValues() []FrameType {
	return _FrameTypeValues
}

// FrameTypeStrings returns a slice of all String values of the enum
func FrameTypeStrings() []string {
	strs := make([]string, len(_FrameTypeNames))
	copy(strs, _FrameTypeNames)
	return strs
}

// IsAFrameType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FrameType) IsAFrameType() bool {
	for _, v := range _FrameTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FrameType
func (i FrameType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FrameType
func (i *FrameType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FrameType should be a string, got %s", data)
	}

	var err error
	*i, err = FrameTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for FrameType
func (i FrameType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FrameType
func (i *FrameType) UnmarshalText(text []byte) error {
	var err error
	*i, err = FrameTypeString(string(text))
	return err
}
